// Real FAANG interview question bank with frequency data

export interface Question {
  id: string
  title: string
  company: string[]
  category: 'DSA' | 'System Design' | 'Behavioral'
  difficulty: 'Easy' | 'Medium' | 'Hard'
  frequency: number // reports in last 6 months
  tags: string[]
  description: string
  lastReported: string
}

export const questionBank: Question[] = [
  // ============ DSA - EASY ============
  {
    id: 'dsa-e-1',
    title: 'Two Sum',
    company: ['Google', 'Amazon', 'Meta'],
    category: 'DSA',
    difficulty: 'Easy',
    frequency: 127,
    tags: ['Arrays', 'Hash Map'],
    description: 'Given an array of integers and a target, return indices of two numbers that add up to target.',
    lastReported: '2026-03-20',
  },
  {
    id: 'dsa-e-2',
    title: 'Valid Parentheses',
    company: ['Google', 'Amazon', 'Apple'],
    category: 'DSA',
    difficulty: 'Easy',
    frequency: 89,
    tags: ['Stack', 'Strings'],
    description: 'Given a string containing brackets, determine if the input string is valid.',
    lastReported: '2026-03-18',
  },
  {
    id: 'dsa-e-3',
    title: 'Merge Two Sorted Lists',
    company: ['Amazon', 'Apple', 'Microsoft'],
    category: 'DSA',
    difficulty: 'Easy',
    frequency: 76,
    tags: ['Linked List', 'Recursion'],
    description: 'Merge two sorted linked lists and return it as a sorted list.',
    lastReported: '2026-03-15',
  },
  {
    id: 'dsa-e-4',
    title: 'Best Time to Buy and Sell Stock',
    company: ['Meta', 'Amazon', 'Google'],
    category: 'DSA',
    difficulty: 'Easy',
    frequency: 94,
    tags: ['Arrays', 'Greedy'],
    description: 'Find the maximum profit from buying and selling one share of stock.',
    lastReported: '2026-03-22',
  },
  {
    id: 'dsa-e-5',
    title: 'Valid Palindrome',
    company: ['Meta', 'Apple'],
    category: 'DSA',
    difficulty: 'Easy',
    frequency: 63,
    tags: ['Two Pointers', 'Strings'],
    description: 'Determine if a string is a palindrome, considering only alphanumeric characters.',
    lastReported: '2026-03-10',
  },
  {
    id: 'dsa-e-6',
    title: 'Maximum Subarray',
    company: ['Google', 'Amazon', 'Netflix'],
    category: 'DSA',
    difficulty: 'Easy',
    frequency: 71,
    tags: ['Arrays', 'Dynamic Programming', 'Kadane'],
    description: 'Find the contiguous subarray with the largest sum.',
    lastReported: '2026-03-19',
  },

  // ============ DSA - MEDIUM ============
  {
    id: 'dsa-m-1',
    title: 'LRU Cache',
    company: ['Google', 'Meta', 'Amazon'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 112,
    tags: ['Hash Map', 'Linked List', 'Design'],
    description: 'Design a data structure that follows LRU cache eviction policy with O(1) get and put.',
    lastReported: '2026-03-21',
  },
  {
    id: 'dsa-m-2',
    title: 'Number of Islands',
    company: ['Amazon', 'Google', 'Meta'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 98,
    tags: ['BFS', 'DFS', 'Graph', 'Matrix'],
    description: 'Count the number of islands in a 2D binary grid.',
    lastReported: '2026-03-23',
  },
  {
    id: 'dsa-m-3',
    title: 'Longest Substring Without Repeating Characters',
    company: ['Google', 'Amazon', 'Apple'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 87,
    tags: ['Sliding Window', 'Hash Map', 'Strings'],
    description: 'Find the length of the longest substring without repeating characters.',
    lastReported: '2026-03-17',
  },
  {
    id: 'dsa-m-4',
    title: 'Merge Intervals',
    company: ['Google', 'Meta', 'Apple'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 79,
    tags: ['Arrays', 'Sorting'],
    description: 'Given a collection of intervals, merge all overlapping intervals.',
    lastReported: '2026-03-14',
  },
  {
    id: 'dsa-m-5',
    title: 'Binary Tree Level Order Traversal',
    company: ['Amazon', 'Meta', 'Apple'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 65,
    tags: ['BFS', 'Tree', 'Queue'],
    description: 'Return the level order traversal of a binary tree\'s values.',
    lastReported: '2026-03-12',
  },
  {
    id: 'dsa-m-6',
    title: 'Top K Frequent Elements',
    company: ['Amazon', 'Netflix', 'Google'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 73,
    tags: ['Heap', 'Hash Map', 'Bucket Sort'],
    description: 'Given an array, return the k most frequent elements.',
    lastReported: '2026-03-16',
  },
  {
    id: 'dsa-m-7',
    title: 'Product of Array Except Self',
    company: ['Meta', 'Amazon', 'Apple'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 68,
    tags: ['Arrays', 'Prefix Sum'],
    description: 'Return an array where each element is the product of all elements except itself, without division.',
    lastReported: '2026-03-11',
  },
  {
    id: 'dsa-m-8',
    title: '3Sum',
    company: ['Google', 'Meta', 'Amazon'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 91,
    tags: ['Arrays', 'Two Pointers', 'Sorting'],
    description: 'Find all unique triplets in the array that sum to zero.',
    lastReported: '2026-03-20',
  },
  {
    id: 'dsa-m-9',
    title: 'Course Schedule',
    company: ['Google', 'Amazon', 'Netflix'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 56,
    tags: ['Graph', 'Topological Sort', 'DFS'],
    description: 'Determine if you can finish all courses given their prerequisites (cycle detection).',
    lastReported: '2026-03-09',
  },
  {
    id: 'dsa-m-10',
    title: 'Subarray Sum Equals K',
    company: ['Meta', 'Google'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 82,
    tags: ['Arrays', 'Hash Map', 'Prefix Sum'],
    description: 'Find the total number of contiguous subarrays whose sum equals k.',
    lastReported: '2026-03-22',
  },

  // ============ DSA - HARD ============
  {
    id: 'dsa-h-1',
    title: 'Median of Two Sorted Arrays',
    company: ['Google', 'Apple', 'Amazon'],
    category: 'DSA',
    difficulty: 'Hard',
    frequency: 45,
    tags: ['Binary Search', 'Arrays'],
    description: 'Find the median of two sorted arrays in O(log(m+n)) time.',
    lastReported: '2026-03-18',
  },
  {
    id: 'dsa-h-2',
    title: 'Trapping Rain Water',
    company: ['Google', 'Amazon', 'Meta'],
    category: 'DSA',
    difficulty: 'Hard',
    frequency: 52,
    tags: ['Two Pointers', 'Stack', 'Arrays'],
    description: 'Compute how much water can be trapped after raining given an elevation map.',
    lastReported: '2026-03-20',
  },
  {
    id: 'dsa-h-3',
    title: 'Word Ladder',
    company: ['Google', 'Amazon'],
    category: 'DSA',
    difficulty: 'Hard',
    frequency: 38,
    tags: ['BFS', 'Graph', 'Strings'],
    description: 'Find the shortest transformation sequence from start word to end word.',
    lastReported: '2026-03-13',
  },
  {
    id: 'dsa-h-4',
    title: 'Serialize and Deserialize Binary Tree',
    company: ['Meta', 'Google', 'Amazon'],
    category: 'DSA',
    difficulty: 'Hard',
    frequency: 41,
    tags: ['Tree', 'BFS', 'DFS', 'Design'],
    description: 'Design an algorithm to serialize and deserialize a binary tree.',
    lastReported: '2026-03-15',
  },
  {
    id: 'dsa-h-5',
    title: 'Minimum Window Substring',
    company: ['Meta', 'Google', 'Apple'],
    category: 'DSA',
    difficulty: 'Hard',
    frequency: 47,
    tags: ['Sliding Window', 'Hash Map', 'Strings'],
    description: 'Find the minimum window substring containing all characters of another string.',
    lastReported: '2026-03-21',
  },

  // ============ SYSTEM DESIGN - EASY ============
  {
    id: 'sd-e-1',
    title: 'Design a URL Shortener',
    company: ['Google', 'Meta', 'Amazon'],
    category: 'System Design',
    difficulty: 'Easy',
    frequency: 104,
    tags: ['Hashing', 'Database', 'Caching'],
    description: 'Design a URL shortening service like bit.ly.',
    lastReported: '2026-03-22',
  },
  {
    id: 'sd-e-2',
    title: 'Design a Rate Limiter',
    company: ['Google', 'Netflix', 'Amazon'],
    category: 'System Design',
    difficulty: 'Easy',
    frequency: 78,
    tags: ['Token Bucket', 'Sliding Window', 'Distributed Systems'],
    description: 'Design an API rate limiter that limits requests per user/IP.',
    lastReported: '2026-03-19',
  },
  {
    id: 'sd-e-3',
    title: 'Design a Paste Bin',
    company: ['Amazon', 'Google'],
    category: 'System Design',
    difficulty: 'Easy',
    frequency: 45,
    tags: ['Storage', 'CDN', 'Database'],
    description: 'Design a service like Pastebin where users can store and share text.',
    lastReported: '2026-03-10',
  },

  // ============ SYSTEM DESIGN - MEDIUM ============
  {
    id: 'sd-m-1',
    title: 'Design Twitter / News Feed',
    company: ['Meta', 'Google', 'Amazon'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 96,
    tags: ['Fan-out', 'Caching', 'Message Queue', 'Database'],
    description: 'Design a social media feed system like Twitter or Facebook News Feed.',
    lastReported: '2026-03-23',
  },
  {
    id: 'sd-m-2',
    title: 'Design a Chat System (WhatsApp)',
    company: ['Meta', 'Google', 'Amazon'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 88,
    tags: ['WebSocket', 'Message Queue', 'Database', 'Presence'],
    description: 'Design a real-time messaging system like WhatsApp or Facebook Messenger.',
    lastReported: '2026-03-21',
  },
  {
    id: 'sd-m-3',
    title: 'Design YouTube / Video Streaming',
    company: ['Google', 'Netflix', 'Amazon'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 72,
    tags: ['CDN', 'Transcoding', 'Storage', 'Streaming'],
    description: 'Design a video upload and streaming platform.',
    lastReported: '2026-03-17',
  },
  {
    id: 'sd-m-4',
    title: 'Design Instagram',
    company: ['Meta', 'Google'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 67,
    tags: ['CDN', 'Feed', 'Storage', 'Caching'],
    description: 'Design a photo-sharing social network like Instagram.',
    lastReported: '2026-03-14',
  },
  {
    id: 'sd-m-5',
    title: 'Design a Notification System',
    company: ['Amazon', 'Meta', 'Apple'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 59,
    tags: ['Message Queue', 'Push Notifications', 'Priority Queue'],
    description: 'Design a scalable notification system supporting push, email, and SMS.',
    lastReported: '2026-03-12',
  },

  // ============ SYSTEM DESIGN - HARD ============
  {
    id: 'sd-h-1',
    title: 'Design Google Search',
    company: ['Google'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 34,
    tags: ['Web Crawler', 'Indexing', 'Ranking', 'Distributed Systems'],
    description: 'Design a web search engine with crawling, indexing, and ranking.',
    lastReported: '2026-03-16',
  },
  {
    id: 'sd-h-2',
    title: 'Design Uber / Lyft',
    company: ['Google', 'Amazon', 'Meta'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 51,
    tags: ['Geospatial', 'Matching', 'Real-time', 'Distributed Systems'],
    description: 'Design a ride-sharing platform with real-time matching and ETA.',
    lastReported: '2026-03-20',
  },
  {
    id: 'sd-h-3',
    title: 'Design a Distributed Cache',
    company: ['Google', 'Amazon', 'Netflix'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 43,
    tags: ['Consistent Hashing', 'Replication', 'Eviction'],
    description: 'Design a distributed caching system like Memcached or Redis cluster.',
    lastReported: '2026-03-18',
  },
  {
    id: 'sd-h-4',
    title: 'Design Google Docs',
    company: ['Google', 'Meta'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 39,
    tags: ['CRDT', 'OT', 'WebSocket', 'Collaboration'],
    description: 'Design a real-time collaborative document editor.',
    lastReported: '2026-03-15',
  },

  // ============ BEHAVIORAL ============
  {
    id: 'beh-1',
    title: 'Tell me about a technically challenging project',
    company: ['Google', 'Meta', 'Apple'],
    category: 'Behavioral',
    difficulty: 'Medium',
    frequency: 134,
    tags: ['Technical', 'Problem Solving', 'STAR'],
    description: 'Describe a project that was technically challenging. What made it hard and how did you approach it?',
    lastReported: '2026-03-23',
  },
  {
    id: 'beh-2',
    title: 'Tell me about a time you disagreed with a teammate',
    company: ['Google', 'Amazon', 'Meta'],
    category: 'Behavioral',
    difficulty: 'Medium',
    frequency: 118,
    tags: ['Conflict Resolution', 'Communication', 'STAR'],
    description: 'How do you handle technical disagreements? Give a specific example.',
    lastReported: '2026-03-22',
  },
  {
    id: 'beh-3',
    title: 'Describe a time you failed',
    company: ['Amazon', 'Netflix', 'Google'],
    category: 'Behavioral',
    difficulty: 'Medium',
    frequency: 95,
    tags: ['Growth Mindset', 'Self-Awareness', 'STAR'],
    description: 'Tell me about a time you failed and what you learned from it.',
    lastReported: '2026-03-19',
  },
  {
    id: 'beh-4',
    title: 'Tell me about a time you went above and beyond',
    company: ['Amazon', 'Apple', 'Meta'],
    category: 'Behavioral',
    difficulty: 'Easy',
    frequency: 107,
    tags: ['Ownership', 'Customer Obsession', 'STAR'],
    description: 'Describe a situation where you exceeded expectations or took ownership.',
    lastReported: '2026-03-21',
  },
  {
    id: 'beh-5',
    title: 'Why do you want to work here?',
    company: ['Google', 'Meta', 'Amazon', 'Apple', 'Netflix'],
    category: 'Behavioral',
    difficulty: 'Easy',
    frequency: 156,
    tags: ['Motivation', 'Culture Fit'],
    description: 'Why this company specifically? What excites you about the role?',
    lastReported: '2026-03-23',
  },
  {
    id: 'beh-6',
    title: 'Tell me about a time you had to make a decision with incomplete information',
    company: ['Amazon', 'Netflix', 'Google'],
    category: 'Behavioral',
    difficulty: 'Hard',
    frequency: 72,
    tags: ['Bias for Action', 'Judgment', 'STAR'],
    description: 'How do you make decisions when you don\'t have all the data?',
    lastReported: '2026-03-17',
  },
  {
    id: 'beh-7',
    title: 'Describe your most impactful project',
    company: ['Meta', 'Google', 'Amazon'],
    category: 'Behavioral',
    difficulty: 'Medium',
    frequency: 89,
    tags: ['Impact', 'Deliver Results', 'STAR'],
    description: 'What project are you most proud of? What was the measurable impact?',
    lastReported: '2026-03-20',
  },

  // ============ MICROSOFT ============
  {
    id: 'ms-dsa-1',
    title: 'Clone Graph',
    company: ['Microsoft', 'Meta', 'Google'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 74,
    tags: ['Graph', 'BFS', 'DFS', 'Hash Map'],
    description: 'Deep copy a graph where each node has neighbors and a random pointer.',
    lastReported: '2026-03-21',
  },
  {
    id: 'ms-dsa-2',
    title: 'Design Browser History',
    company: ['Microsoft', 'Amazon'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 58,
    tags: ['Stack', 'Design', 'Linked List'],
    description: 'Implement forward/back navigation with visit functionality.',
    lastReported: '2026-03-18',
  },
  {
    id: 'ms-sd-1',
    title: 'Design Microsoft Teams',
    company: ['Microsoft'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 82,
    tags: ['WebSocket', 'Video', 'Real-time', 'Presence'],
    description: 'Design a collaboration platform with messaging, video calls, and file sharing.',
    lastReported: '2026-03-22',
  },
  {
    id: 'ms-sd-2',
    title: 'Design Azure Blob Storage',
    company: ['Microsoft', 'Amazon'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 41,
    tags: ['Object Storage', 'Distributed Systems', 'Tiered Storage'],
    description: 'Design a scalable object storage service with tiered access.',
    lastReported: '2026-03-19',
  },

  // ============ NVIDIA ============
  {
    id: 'nv-dsa-1',
    title: 'Parallel Prefix Sum (Scan)',
    company: ['NVIDIA'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 43,
    tags: ['Parallel Computing', 'Arrays', 'GPU'],
    description: 'Implement a parallel prefix sum algorithm optimized for GPU-style execution.',
    lastReported: '2026-03-20',
  },
  {
    id: 'nv-dsa-2',
    title: 'Matrix Multiplication (Tiled)',
    company: ['NVIDIA', 'Google'],
    category: 'DSA',
    difficulty: 'Hard',
    frequency: 37,
    tags: ['Matrix', 'Cache Optimization', 'Parallel Computing'],
    description: 'Implement blocked matrix multiplication optimized for cache hierarchy.',
    lastReported: '2026-03-17',
  },
  {
    id: 'nv-sd-1',
    title: 'Design a GPU Job Scheduler',
    company: ['NVIDIA'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 35,
    tags: ['Scheduling', 'GPU', 'Resource Management'],
    description: 'Design a system that manages kernel launches across multiple GPU streams.',
    lastReported: '2026-03-18',
  },
  {
    id: 'nv-sd-2',
    title: 'Design LLM Inference Serving Platform',
    company: ['NVIDIA', 'Google', 'Meta'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 62,
    tags: ['ML Serving', 'GPU', 'Dynamic Batching', 'Distributed Systems'],
    description: 'Design an inference platform for deploying LLMs across thousands of GPUs.',
    lastReported: '2026-03-23',
  },

  // ============ TESLA ============
  {
    id: 'ts-dsa-1',
    title: 'Real-Time Moving Median Filter',
    company: ['Tesla', 'NVIDIA'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 38,
    tags: ['Heap', 'Sliding Window', 'Real-time'],
    description: 'Implement a real-time moving median filter for noisy sensor data with O(log n) per update.',
    lastReported: '2026-03-19',
  },
  {
    id: 'ts-dsa-2',
    title: 'A* Path Planning',
    company: ['Tesla', 'Uber'],
    category: 'DSA',
    difficulty: 'Hard',
    frequency: 31,
    tags: ['Graph', 'A*', 'Path Planning', 'Priority Queue'],
    description: 'Implement a 2D grid-based path planner with obstacle avoidance using A* search.',
    lastReported: '2026-03-16',
  },
  {
    id: 'ts-sd-1',
    title: 'Design Autopilot Perception Pipeline',
    company: ['Tesla'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 29,
    tags: ['Real-time', 'ML Pipeline', 'Sensor Fusion', 'Edge Computing'],
    description: 'Design the perception pipeline: camera input to object detection to tracking to planning.',
    lastReported: '2026-03-20',
  },
  {
    id: 'ts-sd-2',
    title: 'Design OTA Update System',
    company: ['Tesla', 'Apple'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 44,
    tags: ['Distributed Systems', 'Rollback', 'Fleet Management'],
    description: 'Design an over-the-air software update system for a fleet of vehicles.',
    lastReported: '2026-03-22',
  },

  // ============ UBER ============
  {
    id: 'ub-dsa-1',
    title: 'Geohash Encoding/Decoding',
    company: ['Uber', 'Google'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 55,
    tags: ['Geospatial', 'Hashing', 'Proximity Search'],
    description: 'Implement geohash encoding and use it for proximity search of nearby drivers.',
    lastReported: '2026-03-21',
  },
  {
    id: 'ub-sd-1',
    title: 'Design Ride Matching System',
    company: ['Uber'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 78,
    tags: ['Geospatial', 'Matching', 'Real-time', 'Optimization'],
    description: 'Design a real-time system matching riders to nearby drivers with ETA optimization.',
    lastReported: '2026-03-23',
  },
  {
    id: 'ub-sd-2',
    title: 'Design Surge Pricing',
    company: ['Uber'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 42,
    tags: ['Dynamic Pricing', 'Real-time', 'Supply/Demand'],
    description: 'Design a dynamic pricing system based on real-time supply and demand.',
    lastReported: '2026-03-19',
  },

  // ============ AIRBNB ============
  {
    id: 'ab-dsa-1',
    title: 'Booking Conflict Detection',
    company: ['Airbnb', 'Google'],
    category: 'DSA',
    difficulty: 'Easy',
    frequency: 61,
    tags: ['Intervals', 'Sorting', 'Arrays'],
    description: 'Given booking intervals, determine if a new booking conflicts with existing reservations.',
    lastReported: '2026-03-20',
  },
  {
    id: 'ab-sd-1',
    title: 'Design Airbnb Search & Discovery',
    company: ['Airbnb'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 69,
    tags: ['Search', 'Ranking', 'Geospatial', 'Personalization'],
    description: 'Design the search and discovery system with geospatial search and personalized ranking.',
    lastReported: '2026-03-22',
  },
  {
    id: 'ab-sd-2',
    title: 'Design Dynamic Pricing (Smart Pricing)',
    company: ['Airbnb'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 36,
    tags: ['ML', 'Pricing', 'Seasonality', 'Demand Forecasting'],
    description: 'Design a system suggesting optimal nightly rates based on demand, seasonality, and comparables.',
    lastReported: '2026-03-18',
  },
  {
    id: 'ab-beh-1',
    title: 'Tell me about building with user empathy',
    company: ['Airbnb'],
    category: 'Behavioral',
    difficulty: 'Medium',
    frequency: 87,
    tags: ['User Empathy', 'Product Sense', 'STAR'],
    description: 'How did user empathy influence your technical decisions on a project?',
    lastReported: '2026-03-21',
  },

  // ============ STRIPE ============
  {
    id: 'st-dsa-1',
    title: 'Idempotency Key Store',
    company: ['Stripe'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 48,
    tags: ['Hash Map', 'TTL', 'Design', 'Payments'],
    description: 'Implement an idempotency key store that prevents duplicate payment processing.',
    lastReported: '2026-03-20',
  },
  {
    id: 'st-dsa-2',
    title: 'Payment State Machine',
    company: ['Stripe', 'Amazon'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 52,
    tags: ['State Machine', 'Design', 'Validation'],
    description: 'Design a state machine for payment lifecycle with valid transition enforcement.',
    lastReported: '2026-03-22',
  },
  {
    id: 'st-sd-1',
    title: 'Design Payment Processing Pipeline',
    company: ['Stripe', 'Amazon'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 71,
    tags: ['Payments', 'Distributed Transactions', 'Idempotency'],
    description: 'Design the authorization, capture, settlement pipeline with multiple payment methods.',
    lastReported: '2026-03-23',
  },
  {
    id: 'st-sd-2',
    title: 'Design Distributed Ledger System',
    company: ['Stripe'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 33,
    tags: ['Ledger', 'Double-Entry', 'Multi-Currency', 'Consistency'],
    description: 'Design a double-entry accounting system across millions of merchants with real-time balances.',
    lastReported: '2026-03-19',
  },

  // ============ SPOTIFY ============
  {
    id: 'sp-dsa-1',
    title: 'Playlist Shuffle (No Repeat Artist)',
    company: ['Spotify'],
    category: 'DSA',
    difficulty: 'Easy',
    frequency: 54,
    tags: ['Arrays', 'Greedy', 'Randomization'],
    description: 'Implement a shuffle algorithm that guarantees no artist plays twice in a row when possible.',
    lastReported: '2026-03-21',
  },
  {
    id: 'sp-dsa-2',
    title: 'Streaming Top-K Songs',
    company: ['Spotify', 'Netflix'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 46,
    tags: ['Heap', 'Count-Min Sketch', 'Streaming'],
    description: 'Track the top-K most played songs over a sliding window of play events.',
    lastReported: '2026-03-19',
  },
  {
    id: 'sp-sd-1',
    title: 'Design Audio Streaming & Delivery',
    company: ['Spotify', 'Netflix'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 63,
    tags: ['CDN', 'Adaptive Bitrate', 'Streaming', 'Caching'],
    description: 'Design audio streaming with adaptive bitrate, crossfade, and gapless playback.',
    lastReported: '2026-03-22',
  },
  {
    id: 'sp-sd-2',
    title: 'Design Discover Weekly Pipeline',
    company: ['Spotify'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 39,
    tags: ['Recommendation', 'ML Pipeline', 'Data Processing', 'Personalization'],
    description: 'Design the recommendation pipeline generating personalized playlists for 500M+ users.',
    lastReported: '2026-03-20',
  },

  // ============ ORACLE ============
  {
    id: 'or-dsa-1',
    title: 'B-Tree Insert with Splitting',
    company: ['Oracle'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 34,
    tags: ['Trees', 'Database', 'B-Tree'],
    description: 'Implement B-tree insert operation and explain the node splitting mechanism.',
    lastReported: '2026-03-17',
  },
  {
    id: 'or-dsa-2',
    title: 'Deadlock Detector',
    company: ['Oracle', 'Google'],
    category: 'DSA',
    difficulty: 'Hard',
    frequency: 28,
    tags: ['Graph', 'Cycle Detection', 'Concurrency'],
    description: 'Implement a deadlock detector using cycle detection in a wait-for graph.',
    lastReported: '2026-03-15',
  },
  {
    id: 'or-sd-1',
    title: 'Design Distributed SQL Query Executor',
    company: ['Oracle', 'Google'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 31,
    tags: ['Database', 'Query Optimization', 'Distributed Systems'],
    description: 'Design a distributed query executor that pushes computation to data nodes.',
    lastReported: '2026-03-18',
  },

  // ============ BLOOMBERG ============
  {
    id: 'bb-dsa-1',
    title: 'Order Book (Best Bid/Ask)',
    company: ['Bloomberg'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 57,
    tags: ['Heap', 'Design', 'Financial', 'Sorted Map'],
    description: 'Implement an order book supporting add/cancel/execute with O(log n) insert and O(1) best price.',
    lastReported: '2026-03-22',
  },
  {
    id: 'bb-dsa-2',
    title: 'Lock-Free SPSC Queue',
    company: ['Bloomberg', 'NVIDIA'],
    category: 'DSA',
    difficulty: 'Hard',
    frequency: 25,
    tags: ['Concurrency', 'Lock-Free', 'Atomics', 'C++'],
    description: 'Implement a lock-free single producer single consumer queue using atomics.',
    lastReported: '2026-03-16',
  },
  {
    id: 'bb-sd-1',
    title: 'Design Real-Time Market Data System',
    company: ['Bloomberg'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 53,
    tags: ['Low Latency', 'Real-time', 'Financial', 'Messaging'],
    description: 'Design a system delivering price updates to 300K+ terminals with sub-millisecond latency.',
    lastReported: '2026-03-21',
  },

  // ============ IBM ============
  {
    id: 'ibm-dsa-1',
    title: 'Consistent Hashing Ring',
    company: ['IBM', 'Amazon', 'Netflix'],
    category: 'DSA',
    difficulty: 'Medium',
    frequency: 49,
    tags: ['Hashing', 'Distributed Systems', 'Virtual Nodes'],
    description: 'Implement a consistent hashing ring with virtual nodes for a distributed cache.',
    lastReported: '2026-03-20',
  },
  {
    id: 'ibm-sd-1',
    title: 'Design Hybrid Cloud Deployment Platform',
    company: ['IBM', 'Microsoft'],
    category: 'System Design',
    difficulty: 'Medium',
    frequency: 38,
    tags: ['Cloud', 'Multi-Cloud', 'Kubernetes', 'Enterprise'],
    description: 'Design a platform managing workloads across on-premise and multiple cloud providers.',
    lastReported: '2026-03-19',
  },
  {
    id: 'ibm-sd-2',
    title: 'Design Federated Learning Platform',
    company: ['IBM', 'Google'],
    category: 'System Design',
    difficulty: 'Hard',
    frequency: 26,
    tags: ['ML', 'Privacy', 'Distributed Systems', 'Enterprise'],
    description: 'Design a federated learning platform that trains models across organizations without sharing raw data.',
    lastReported: '2026-03-17',
  },
]

export function filterQuestions(filters: {
  company?: string
  category?: string
  difficulty?: string
  search?: string
}): Question[] {
  let filtered = [...questionBank]

  if (filters.company) {
    filtered = filtered.filter((q) => q.company.includes(filters.company!))
  }
  if (filters.category) {
    filtered = filtered.filter((q) => q.category === filters.category)
  }
  if (filters.difficulty) {
    filtered = filtered.filter((q) => q.difficulty === filters.difficulty)
  }
  if (filters.search) {
    const term = filters.search.toLowerCase()
    filtered = filtered.filter(
      (q) =>
        q.title.toLowerCase().includes(term) ||
        q.description.toLowerCase().includes(term) ||
        q.tags.some((t) => t.toLowerCase().includes(term))
    )
  }

  return filtered.sort((a, b) => b.frequency - a.frequency)
}
